on:
  push:
    branches:
    - main
jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
       - shell: bash
         env:
           SSH_KEY: ${{ secrets.SSH_RSA_KEY }}
         run: |
           echo SSH_KEY | cat /dev/stdin
